### ISSUE TITLE
Bars from Create Deco use Iron Bars textures with this mod

### ISSUE THREAD

**Issue by mdujovic17** [CodenameRevy/additional-bars-fabric#13]
@gamma1772 the Z fighting on classic vertical bar persist (horizontal fixed)
![image](https://user-images.githubusercontent.com/82106625/176486108-78d4f458-4dde-43a2-84d5-cc9a6f53c89e.png)
It also break bars from [CreateDeco](https://www.curseforge.com/minecraft/mc-mods/create-deco) and other mods, all become iron :
![image](https://user-images.githubusercontent.com/82106625/176486578-16cf5954-3e4b-4ad5-902c-6149568130bc.png)

_Originally posted by @ardissaps in https://github.com/gamma1772/AdditionalBarsFabric/issues/12#issuecomment-1170198166_

**Comment by ardissaps** [comment]
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Additional Bars' (additionalbars) 3.2.0+1.18.2 with any version that is compatible with:
		 - minecraft 1.18.2
Unmet dependency listing:
	 - Mod 'Additional Bars' (additionalbars) 3.2.0+1.18.2 requires any 1.19.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.18.2!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
![image](https://user-images.githubusercontent.com/82106625/176700728-137897d8-7129-41bd-ba2a-492d78f0cf72.png)
